import {
  Pizza,
  Amphora,
  Coffee,
  ForkKnife,
  Soup,
  IceCream,
  Cake,
  Apple,
  Martini,
  Carrot,
  Egg,
  Donut,
  Fish,
  Cherry,
  Citrus,
  Wine,
  Beer,
  Milk,
  GlassWater,
  File,
  Search,
  Check,
  Trash,
  Package,
  Package2,
  LibraryBig,
  Shirt,
} from "lucide-react";

const categorizedIcons = {
  food: [
    { name: "Pizza", component: <Pizza /> },
    { name: "Amphora", component: <Amphora /> },
    { name: "Coffee", component: <Coffee /> },
    { name: "ForkKnife", component: <ForkKnife /> },
    { name: "Soup", component: <Soup /> },
    { name: "IceCream", component: <IceCream /> },
    { name: "Cake", component: <Cake /> },
    { name: "Apple", component: <Apple /> },
    { name: "Carrot", component: <Carrot /> },
    { name: "Egg", component: <Egg /> },
    { name: "Donut", component: <Donut /> },
    { name: "Fish", component: <Fish /> },
    { name: "Cherry", component: <Cherry /> },
    { name: "Citrus", component: <Citrus /> },
  ],

  beverages: [
    { name: "Wine", component: <Wine /> },
    { name: "Beer", component: <Beer /> },
    { name: "Milk", component: <Milk /> },
    { name: "GlassWater", component: <GlassWater /> },
    { name: "Maritini", component: <Martini /> },
  ],

  utilities: [
    { name: "File", component: <File /> },
    { name: "Search", component: <Search /> },
    { name: "Check", component: <Check /> },
    { name: "Trash", component: <Trash /> },
    { name: "Package", component: <Package /> },
    { name: "Package2", component: <Package2 /> },
    { name: "LibraryBig", component: <LibraryBig /> },
    { name: "Shirt", component: <Shirt /> },
  ],
};

export default categorizedIcons;
